name: Docker build

on:
  push:
    branches:
      - master
      - main
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: selfsimilar
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Prepare
        run: make prepare

      - name: Build
        run: make build

      - name: Upload target content
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target

      - name: Test Docsy
        run: make test-docsy

      - name: Test DocuAPI
        run: make test-docuapi

      - name: Push egde images
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: make push-edge

      - name: Push images
        if: "startsWith(github.ref, 'refs/tags/')"
        run: make push-release
